name: Windows
env:
  VK_VERSION: 1.3.224.1
on:
  push:
    branches:
      - master

jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v3

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: $VK_VERSION
          cache: true
      - name: Build vkQuake2 Debug (x64)
        run: msbuild quake2.sln /m /t:Rebuild /p:Configuration=Debug /p:Platform=x64
      - name: Upload vkQuake2 Debug (x64) artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-Windows-debug-x64
          path: |
            Quake2
            !Quake2/**/*.obj
            !Quake2/**/*.exp
            !Quake2/**/*.ilk
            !Quake2/**/*.lib
            !Quake2/**/*.pdb
            !Quake2/**/*.iobj
            !Quake2/**/*.ipdb
      - name: Build vkQuake2 Release (x64)
        run: msbuild quake2.sln /m /t:Rebuild /p:Configuration=Release /p:Platform=x64
      - name: Upload vkQuake2 Release (x64) artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-Windows-release-x64
          path: |
            Quake2
            !Quake2/**/*.obj
            !Quake2/**/*.exp
            !Quake2/**/*.ilk
            !Quake2/**/*.lib
            !Quake2/**/*.pdb
            !Quake2/**/*.iobj
            !Quake2/**/*.ipdb
