name: Linux
env:
  VK_VERSION: 1.3.224.1
on:
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install required packages
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y yad make gcc g++ mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: $VK_VERSION
          cache: true
      - name: Build vkQuake2 Debug
        shell: bash
        run: |
          cd linux
          make clean debug
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-Ubuntu-debug-x64
          path: |
            linux/debugx64
            !linux/debugx64/**/*.o
      - name: Build vkQuake2 Release
        shell: bash
        run: |
          cd linux
          make clean release
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-Ubuntu-release-x64
          path: |
            linux/releasex64
            !linux/releasex64/**/*.o

      - name: Build vkQuake2 appImage
        shell: bash
        run: |
           linux/appimage/appimage.sh
      - name: Upload vkQuake2 AppImage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-AppImage
          path: |
            vkQuake.AppImage
