name: MacOS
env:
  VK_VERSION: 1.3.224.1
on:
  push:
    branches:
      - master

jobs:
  MacOS:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: $VK_VERSION
          cache: true
      - name: Build vkQuake2 Debug
        run: |
          cd macos
          make clean-xcode debug-xcode
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-MacOS-debug-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
      - name: Build vkQuake2 Release
        run: |
          cd macos
          make clean-xcode release-xcode
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vkQuake2-MacOS-release-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
